name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # Get repository files
      - name: Checkout
        uses: actions/checkout@v4


      # Setup Node for minifiers
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      # Install minification tools
      - name: Install Minifiers
        run: |
          npm install -g html-minifier-terser
          npm install -g clean-css-cli
          npm install -g terser


      # Create deployment folder
      - name: Create dist folder
        run: |
          mkdir dist
          rsync -av \
          --exclude=.git \
          --exclude=.github \
          ./ dist/


      # Replace __VERSION__ with Git commit hash
      - name: Add Version Hash
        run: |
          VERSION=$(git rev-parse --short HEAD)

          echo "Version: $VERSION"

          find dist -type f -name "*.html" -exec \
          sed -i "s/__VERSION__/$VERSION/g" {} \;


      # Update sitemap date
      - name: Update sitemap date
        run: |
          DATE=$(git log -1 --format=%cs)

          echo "Sitemap date: $DATE"

          sed -i "s/__DATE__/$DATE/g" dist/sitemap.xml


      # Minify HTML
      - name: Minify HTML
        run: |
          find dist -type f -name "*.html" -exec \
          html-minifier-terser \
          --collapse-whitespace \
          --remove-comments \
          --remove-optional-tags \
          --remove-redundant-attributes \
          --remove-script-type-attributes \
          --use-short-doctype \
          --minify-css true \
          --minify-js true \
          -o {} {} \;


      # Minify CSS
      - name: Minify CSS
        run: |
          find dist -type f -name "*.css" -exec \
          cleancss \
          -o {} {} \;


      # Minify Javascript
      - name: Minify JS
        run: |
          find dist -type f -name "*.js" -exec \
          terser {} \
          --compress \
          --mangle \
          -o {} \;


      # Upload build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist



  deploy:

    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}


    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
